/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import auxiliares.CameraTools;
import controladores.CamaraPortatilControlador;
import guiif.JfCamaraPortatilIf;
import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Fernando
 */
public class JfCamaraPortatil extends javax.swing.JFrame implements JfCamaraPortatilIf{

    private CamaraPortatilControlador controlador;
    static JLabel foto2;
    static JDialog dialogo2;
    static JfMenuClientes ruta2;
    /**
     * Creates new form JfCamaraPortatil
     */
    public JfCamaraPortatil() {
        initComponents();
        add(jPanel1, BorderLayout.SOUTH);
        controlador = new CamaraPortatilControlador(this, CameraTools.getInstance(400, 400, jpCamara, this), foto2, dialogo2, ruta2);
    }
    
    public static JfCamaraPortatil getInstance(JLabel foto, JDialog dialogo, JfMenuClientes ruta) {
        foto2 = foto;
        dialogo2 = dialogo;
        ruta2 = ruta;
        return JfCamaraPortatilHolder.INSTANCE;
    }

    @Override
    public void setJpCamara(JPanel jpCamara) {
        this.jpCamara = jpCamara;
    }

    @Override
    public JPanel getJpCamra() {
        return jpCamara;
    }

    @Override
    public JButton getJbTomar() {
        return jbTomar;
    }

    @Override
    public void setJbTomar(JButton jbTomar) {
        this.jbTomar = jbTomar;
    }

    @Override
    public JButton getJbRepetir() {
        return jbRepetir;
    }

    @Override
    public void setJbRepetir(JButton jbRepetir) {
        this.jbRepetir = jbRepetir;
    }

    @Override
    public JButton getJbAceptar() {
        return jbAceptar;
    }

    @Override
    public void setJbAceptar(JButton jbAceptar) {
        this.jbAceptar = jbAceptar;
    }
    
    private static class JfCamaraPortatilHolder {

        private static final JfCamaraPortatil INSTANCE = new JfCamaraPortatil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCamara = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jbTomar = new javax.swing.JButton();
        jbRepetir = new javax.swing.JButton();
        jbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 400));

        jpCamara.setPreferredSize(new java.awt.Dimension(350, 350));

        javax.swing.GroupLayout jpCamaraLayout = new javax.swing.GroupLayout(jpCamara);
        jpCamara.setLayout(jpCamaraLayout);
        jpCamaraLayout.setHorizontalGroup(
            jpCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jpCamaraLayout.setVerticalGroup(
            jpCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        getContentPane().add(jpCamara, java.awt.BorderLayout.CENTER);

        jbTomar.setText("Tomar");
        jPanel1.add(jbTomar);

        jbRepetir.setText("Repetir");
        jPanel1.add(jbRepetir);

        jbAceptar.setText("Aceptar");
        jbAceptar.setEnabled(false);
        jPanel1.add(jbAceptar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfCamaraPortatil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfCamaraPortatil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfCamaraPortatil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfCamaraPortatil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfCamaraPortatil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbRepetir;
    private javax.swing.JButton jbTomar;
    private javax.swing.JPanel jpCamara;
    // End of variables declaration//GEN-END:variables
}
